name: mysql-TM
services:
  mysql:
    image: mysql:latest
    container_name: mysql-TM
    environment:
      MYSQL_ROOT_PASSWORD: TMPass
      MYSQL_DATABASE: TaskManagement
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: